/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ExpensesLazyImport = createFileRoute('/expenses')()
const AboutLazyImport = createFileRoute('/about')()
const FinancialQuizLazyImport = createFileRoute('/FinancialQuiz')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ExpensesLazyRoute = ExpensesLazyImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/expenses.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const FinancialQuizLazyRoute = FinancialQuizLazyImport.update({
  id: '/FinancialQuiz',
  path: '/FinancialQuiz',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/FinancialQuiz.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/FinancialQuiz': {
      id: '/FinancialQuiz'
      path: '/FinancialQuiz'
      fullPath: '/FinancialQuiz'
      preLoaderRoute: typeof FinancialQuizLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/FinancialQuiz': typeof FinancialQuizLazyRoute
  '/about': typeof AboutLazyRoute
  '/expenses': typeof ExpensesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/FinancialQuiz': typeof FinancialQuizLazyRoute
  '/about': typeof AboutLazyRoute
  '/expenses': typeof ExpensesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/FinancialQuiz': typeof FinancialQuizLazyRoute
  '/about': typeof AboutLazyRoute
  '/expenses': typeof ExpensesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/FinancialQuiz' | '/about' | '/expenses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/FinancialQuiz' | '/about' | '/expenses'
  id: '__root__' | '/' | '/FinancialQuiz' | '/about' | '/expenses'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FinancialQuizLazyRoute: typeof FinancialQuizLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ExpensesLazyRoute: typeof ExpensesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FinancialQuizLazyRoute: FinancialQuizLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ExpensesLazyRoute: ExpensesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/FinancialQuiz",
        "/about",
        "/expenses"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/FinancialQuiz": {
      "filePath": "FinancialQuiz.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/expenses": {
      "filePath": "expenses.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
