/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SmartAssistantImport } from './routes/smart-assistant'

// Create Virtual Routes

const ExpensesLazyImport = createFileRoute('/expenses')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ExpensesLazyRoute = ExpensesLazyImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/expenses.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SmartAssistantRoute = SmartAssistantImport.update({
  id: '/smart-assistant',
  path: '/smart-assistant',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/smart-assistant': {
      id: '/smart-assistant'
      path: '/smart-assistant'
      fullPath: '/smart-assistant'
      preLoaderRoute: typeof SmartAssistantImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/smart-assistant': typeof SmartAssistantRoute
  '/about': typeof AboutLazyRoute
  '/expenses': typeof ExpensesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/smart-assistant': typeof SmartAssistantRoute
  '/about': typeof AboutLazyRoute
  '/expenses': typeof ExpensesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/smart-assistant': typeof SmartAssistantRoute
  '/about': typeof AboutLazyRoute
  '/expenses': typeof ExpensesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/smart-assistant' | '/about' | '/expenses'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/smart-assistant' | '/about' | '/expenses'
  id: '__root__' | '/' | '/smart-assistant' | '/about' | '/expenses'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SmartAssistantRoute: typeof SmartAssistantRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ExpensesLazyRoute: typeof ExpensesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SmartAssistantRoute: SmartAssistantRoute,
  AboutLazyRoute: AboutLazyRoute,
  ExpensesLazyRoute: ExpensesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/smart-assistant",
        "/about",
        "/expenses"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/smart-assistant": {
      "filePath": "smart-assistant.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/expenses": {
      "filePath": "expenses.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
